name: Integration Test - PR 2165

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - main

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Create artifact 1
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-1" > artifact-1.txt
          
      - name: Upload artifact 1
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-1
          path: artifact-1.txt

      - name: Create artifact 2
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-2" > artifact-2.txt
          
      - name: Upload artifact 2
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-2
          path: artifact-2.txt

      - name: Create artifact 3
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-3" > artifact-3.txt
          
      - name: Upload artifact 3
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-3
          path: artifact-3.txt

      - name: Create artifact 4
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-4" > artifact-4.txt
          
      - name: Upload artifact 4
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-4
          path: artifact-4.txt

      - name: Create artifact 5
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-5" > artifact-5.txt
          
      - name: Upload artifact 5
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-5
          path: artifact-5.txt

      - name: Create artifact 6
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-6" > artifact-6.txt
          
      - name: Upload artifact 6
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-6
          path: artifact-6.txt

      - name: Create artifact 7
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-7" > artifact-7.txt
          
      - name: Upload artifact 7
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-7
          path: artifact-7.txt

      - name: Create artifact 8
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-8" > artifact-8.txt
          
      - name: Upload artifact 8
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-8
          path: artifact-8.txt

      - name: Create artifact 9
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-9" > artifact-9.txt
          
      - name: Upload artifact 9
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-9
          path: artifact-9.txt

      - name: Create artifact 10
        run: echo "Artifact ${{ matrix.batch }}-${{ matrix.index }}-10" > artifact-10.txt
          
      - name: Upload artifact 10
        uses: actions/upload-artifact@v4
        with:
          name: pagination-test-${{ matrix.batch }}-${{ matrix.index }}-10
          path: artifact-10.txt

  # Test pagination - download all 1,100 artifacts (forces 11 pages since page size is 100)
  test-pagination:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: ./
        with:
          pattern: pagination-test-*
          path: download-pagination
        env:
          ACTIONS_ARTIFACT_MAX_ARTIFACT_COUNT: "2000"
          
      - name: Verify all 1,100 artifacts downloaded
        run: |
          echo "Verifying 1,100 artifacts were downloaded (tests pagination across 11 pages)..."
          count=$(find download-pagination -name "artifact-*.txt" | wc -l)
          echo "Found $count artifacts"
          if [ "$count" -eq 1100 ]; then
            echo "✅ Pagination test successful - all 1,100 artifacts downloaded"
          else
            echo "❌ Expected 1,100 artifacts, found $count"
            exit 1
          fi

  # Summary job
  integration-test-summary:
    needs: 
      - test-pagination
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check test results
        run: |
          echo "🧪 Integration Test Summary - PR #2165"
          echo "======================================"
          echo "Pagination Fix: ${{ needs.test-pagination.result }}"
          echo "Configurable Max Count: ${{ needs.test-max-artifact-count.result }}"
          
          if [ "${{ needs.test-pagination.result }}" == "success" ]; then
            echo ""
            echo "✅ All PR #2165 tests passed!"
            exit 0
          else
            echo ""
            echo "❌ Some PR #2165 tests failed!"
            exit 1
          fi
